### ISSUE TITLE
Fails to build on macOS node 6.11.5

### ISSUE THREAD

**Issue by kickthedragon** [Dezeiraud/bsdiff-nodejs#1]
npm ERR! Darwin 17.4.0
npm ERR! argv "/.nvm/versions/node/v6.11.5/bin/node" "
/.nvm/versions/node/v6.11.5/bin/npm" "install" "bsdiff-nodejs" "--save"
npm ERR! node v6.11.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! bsdiff-nodejs@1.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bsdiff-nodejs@1.0.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bsdiff-nodejs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bsdiff-nodejs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bsdiff-nodejs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!    npm-debug.log
$ npm install Dezeiraud/bsdiff-nodejs

> bsdiff-nodejs@1.0.2 install/node_modules/bsdiff-nodejs
> node-gyp rebuild

  CXX(target) Release/obj.target/bsdiff/src/main.o
  CC(target) Release/obj.target/bsdiff/src/bsdiff/bsdiff.o
../src/bsdiff/bsdiff.c:224:32: error: use of undeclared identifier 'O_BINARY'
        if(((fd=open(oldfile,O_RDONLY|O_BINARY|O_NOINHERIT,0))<0) ||
                                      ^
../src/bsdiff/bsdiff.c:224:41: error: use of undeclared identifier 'O_NOINHERIT'
        if(((fd=open(oldfile,O_RDONLY|O_BINARY|O_NOINHERIT,0))<0) ||
                                               ^
../src/bsdiff/bsdiff.c:246:32: error: use of undeclared identifier 'O_BINARY'
        if(((fd=open(newfile,O_RDONLY|O_BINARY|O_NOINHERIT,0))<0) ||
                                      ^
../src/bsdiff/bsdiff.c:246:41: error: use of undeclared identifier 'O_NOINHERIT'
        if(((fd=open(newfile,O_RDONLY|O_BINARY|O_NOINHERIT,0))<0) ||
                                               ^
4 errors generated.
make: *** [Release/obj.target/bsdiff/src/bsdiff/bsdiff.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/.nvm/versions/node/v6.11.5/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Darwin 17.4.0
gyp ERR! command "/.nvm/versions/node/v6.11.5/bin/node" "//.nvm/versions/node/v6.11.5/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /node_modules/bsdiff-nodejs
gyp ERR! node -v v6.11.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

**Comment by Brouilles** [comment]
Hi, 
Thanks for your feedback. We fix this error in this commit https://github.com/Dezeiraud/bsdiff-nodejs/commit/0db3658282d65eb6ae7b9c1edbcee5310b069168. And the version 1.0.3 with this fix is available on npm. I invite you to update. 

I do not have a Mac at my disposal, so there can potentially be errors, do not hesitate to share it here.
Have a good day.

**Comment by Brouilles** [comment]
Now 1.0.4 available https://github.com/Dezeiraud/bsdiff-nodejs/commit/3c2a86786ad25c6c8bf88ae00089691314505459
